server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.96.132:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.96.132

  rabbitmq:
    host: 192.168.96.132

jwt:
  config:
    key: itcast
    ttl: 3600000  #一个小时